version: 2.1
parameters:
  context_name:
    type: string
    default: << pipeline.git.branch >>
workflows:
  version: 2
  test:
    jobs:
    - test:
        context: << pipeline.parameters.context_name >>


jobs:
  test:
    resource_class: co-design-models/r1
    docker:
    - image: ${DOCKER_REGISTRY}/${DOCKER_TARGET_ORG}/${DOCKER_REPO_PREFIX}zuper-mcdp-deploy:${Z_DISTRO}
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    steps:
    - checkout

    - run:
        name: run
        # language=bash
        command: |
          mcdp-load-libraries 
