version: 2.1
workflows: 
  test:
    jobs:
    - test-stage:
        context: z7-stage 
        
jobs:
  test-stage: 
    docker:
      - image: ${DOCKER_REGISTRY}/${DOCKER_TARGET_ORG}/${DOCKER_REPO_PREFIX}zuper-mcdp-deploy:${Z_DISTRO}
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
    - checkout

    - run:
        name: run
        # language=bash
        command: |
          mcdp-load-libraries 
    
    